package completion

import (
	"testing"

	"gotest.tools/v3/assert"
)

func TestGenerateFish(t *testing.T) {
	spec := Spec{
		GlobalFlags: []Flag{{Name: "socket", Short: 0, Help: "Socket path.", HasValue: true}},
		Commands: []Command{
			{
				Name:        "attach",
				Aliases:     []string{"a"},
				Help:        "Attach to a session.",
				Positionals: []Positional{{Name: "session", DynamicTopic: "sessions"}},
			},
			{
				Name:    "list",
				Aliases: []string{"ls"},
				Help:    "List sessions.",
				Flags:   []Flag{{Name: "all", Short: 'a', Help: "Show dead sessions.", HasValue: false}},
			},
		},
	}

	got, err := Generate("fish", "ht", "__complete", spec)
	assert.NilError(t, err)

	expected := "# fish shell completion for ht\n" +
		"# generated by hauntty\n" +
		"complete -c ht -f -x -l socket -d \"Socket path.\"\n" +
		"complete -c ht -f -n '__fish_use_subcommand' -a attach -d \"Attach to a session.\"\n" +
		"complete -c ht -f -n '__fish_use_subcommand' -a a -d \"Attach to a session.\"\n" +
		"complete -c ht -f -n '__fish_seen_subcommand_from attach a' -a \"(ht __complete sessions)\" -d \"session\"\n" +
		"complete -c ht -f -n '__fish_use_subcommand' -a list -d \"List sessions.\"\n" +
		"complete -c ht -f -n '__fish_use_subcommand' -a ls -d \"List sessions.\"\n" +
		"complete -c ht -f -n '__fish_seen_subcommand_from list ls' -s a -l all -d \"Show dead sessions.\"\n"

	assert.Equal(t, got, expected)
}

func TestGenerateZsh(t *testing.T) {
	spec := Spec{
		GlobalFlags: []Flag{{Name: "socket", Help: "Socket path.", HasValue: true}},
		Commands: []Command{
			{
				Name:        "attach",
				Aliases:     []string{"a"},
				Help:        "Attach to a session.",
				Positionals: []Positional{{Name: "session", DynamicTopic: "sessions"}},
			},
		},
	}

	got, err := Generate("zsh", "ht", "__complete", spec)
	assert.NilError(t, err)

	expected := "#compdef ht\n" +
		"compdef _ht ht\n" +
		"_ht() {\n" +
		"  local line state\n" +
		"  _arguments -S -C -s \\\n" +
		"    '--socket=[Socket path.]:value:' \\\n" +
		"    \"1: :->cmds\" \\\n" +
		"    \"*::arg:->args\"\n" +
		"  case \"$state\" in\n" +
		"    cmds)\n" +
		"      _values \"ht command\" \\\n" +
		"        \"attach[Attach to a session.]\" \\\n" +
		"        \"a[Attach to a session.]\"\n" +
		"      ;;\n" +
		"    args)\n" +
		"      case \"$line[1]\" in\n" +
		"        attach|a) _ht_attach;;\n" +
		"      esac\n" +
		"      ;;\n" +
		"  esac\n" +
		"}\n" +
		"_ht_attach() {\n" +
		"  _arguments \\\n" +
		"    '1:session:($(ht __complete sessions))'\n" +
		"}\n"

	assert.Equal(t, got, expected)
}

func TestGenerateBash(t *testing.T) {
	spec := Spec{
		Commands: []Command{{Name: "attach", Aliases: []string{"a"}, Positionals: []Positional{{Name: "session", DynamicTopic: "sessions"}}}},
	}

	got, err := Generate("bash", "ht", "__complete", spec)
	assert.NilError(t, err)

	expected := "# bash completion for ht\n" +
		"_ht_complete() {\n" +
		"  local cur prev cmd\n" +
		"  COMPREPLY=()\n" +
		"  cur=${COMP_WORDS[COMP_CWORD]}\n" +
		"  prev=${COMP_WORDS[COMP_CWORD-1]}\n" +
		"  cmd=${COMP_WORDS[1]}\n\n" +
		"  if [[ ${COMP_CWORD} -eq 1 ]]; then\n" +
		"    COMPREPLY=( $(compgen -W \"a attach\" -- \"$cur\") )\n" +
		"    return 0\n" +
		"  fi\n\n" +
		"  case \"$cmd\" in\n" +
		"    attach|a)\n" +
		"      if [[ ${COMP_CWORD} -eq 2 ]]; then\n" +
		"        COMPREPLY=( $(compgen -W \"$(ht __complete sessions)\" -- \"$cur\") )\n" +
		"        return 0\n" +
		"      fi\n" +
		"      ;;\n" +
		"  esac\n" +
		"}\n" +
		"complete -F _ht_complete ht\n"

	assert.Equal(t, got, expected)
}

func TestGenerateUnsupportedShell(t *testing.T) {
	_, err := Generate("tcsh", "ht", "__complete", Spec{})
	assert.Error(t, err, "unsupported shell: tcsh")
}
