package protocol

// Message is the interface implemented by all protocol messages.
// encode/decode and Type() are generated by protogen.
type Message interface {
	Type() uint8
	encode(*Encoder) error
	decode(*Decoder) error
}

type Session struct {
	Name      string
	State     string
	Cols      uint16
	Rows      uint16
	PID       uint32
	CreatedAt uint32
	CWD       string
}

type DaemonStatus struct {
	PID          uint32
	Uptime       uint32
	SocketPath   string
	RunningCount uint32
	DeadCount    uint32
	Version      string
}

type SessionStatus struct {
	Name           string
	State          string
	Cols           uint16
	Rows           uint16
	PID            uint32
	CWD            string
	ClientCount    uint32
	ClientVersions []string
}

//proto:msg 0x01
type Attach struct {
	Name            string
	Cols            uint16
	Rows            uint16
	Xpixel          uint16
	Ypixel          uint16
	Command         []string
	Env             []string
	ScrollbackLines uint32
	CWD             string
	ReadOnly        bool
}

//proto:msg 0x02
type Input struct {
	Data []byte
}

//proto:msg 0x03
type Resize struct {
	Cols   uint16
	Rows   uint16
	Xpixel uint16
	Ypixel uint16
}

//proto:msg 0x04
type Detach struct {
	Name string
}

//proto:msg 0x05
type List struct{}

//proto:msg 0x06
type Kill struct {
	Name string
}

//proto:msg 0x07
type Send struct {
	Name string
	Data []byte
}

//proto:msg 0x08
type Dump struct {
	Name   string
	Format uint8
}

//proto:msg 0x09
type Prune struct{}

//proto:msg 0x0A
type SendKey struct {
	Name    string
	KeyCode uint32
	Mods    uint32
}

//proto:msg 0x0C
type Status struct {
	SessionName string
}

//proto:msg 0x80
type OK struct {
	SessionName string
	Cols        uint16
	Rows        uint16
	PID         uint32
	Created     bool
}

//proto:msg 0x81
type Error struct {
	Code    uint16
	Message string
}

//proto:msg 0x82
type Output struct {
	Data []byte
}

//proto:msg 0x83
type State struct {
	ScreenDump        []byte
	CursorRow         uint32
	CursorCol         uint32
	IsAlternateScreen bool
}

//proto:msg 0x84
type Sessions struct {
	Sessions []Session
}

//proto:msg 0x85
type Exited struct {
	ExitCode int32
}

//proto:msg 0x86
type DumpResponse struct {
	Data []byte
}

//proto:msg 0x87
type PruneResponse struct {
	Count uint32
}

//proto:msg 0x88
type ClientsChanged struct {
	Count uint16
	Cols  uint16
	Rows  uint16
}

//proto:msg 0x89
type StatusResponse struct {
	Daemon  DaemonStatus
	Session *SessionStatus
}
