// Code generated by protogen. DO NOT EDIT.

package protocol

import "fmt"

const (
	TypeAttach         uint8 = 0x01
	TypeInput          uint8 = 0x02
	TypeResize         uint8 = 0x03
	TypeDetach         uint8 = 0x04
	TypeList           uint8 = 0x05
	TypeKill           uint8 = 0x06
	TypeSend           uint8 = 0x07
	TypeDump           uint8 = 0x08
	TypePrune          uint8 = 0x09
	TypeSendKey        uint8 = 0x0a
	TypeStatus         uint8 = 0x0c
	TypeOK             uint8 = 0x80
	TypeError          uint8 = 0x81
	TypeOutput         uint8 = 0x82
	TypeState          uint8 = 0x83
	TypeSessions       uint8 = 0x84
	TypeExited         uint8 = 0x85
	TypeDumpResponse   uint8 = 0x86
	TypePruneResponse  uint8 = 0x87
	TypeClientsChanged uint8 = 0x88
	TypeStatusResponse uint8 = 0x89
)

func (m *Attach) Type() uint8 { return TypeAttach }

func (m *Attach) encode(e *Encoder) error {
	if err := e.WriteString(m.Name); err != nil {
		return err
	}
	if err := e.WriteU16(m.Cols); err != nil {
		return err
	}
	if err := e.WriteU16(m.Rows); err != nil {
		return err
	}
	if err := e.WriteU16(m.Xpixel); err != nil {
		return err
	}
	if err := e.WriteU16(m.Ypixel); err != nil {
		return err
	}
	if err := e.WriteU32(uint32(len(m.Command))); err != nil {
		return err
	}
	for _, v := range m.Command {
		if err := e.WriteString(v); err != nil {
			return err
		}
	}
	if err := e.WriteU32(uint32(len(m.Env))); err != nil {
		return err
	}
	for _, v := range m.Env {
		if err := e.WriteString(v); err != nil {
			return err
		}
	}
	if err := e.WriteU32(m.ScrollbackLines); err != nil {
		return err
	}
	if err := e.WriteString(m.CWD); err != nil {
		return err
	}
	if err := e.WriteBool(m.ReadOnly); err != nil {
		return err
	}
	return nil
}

func (m *Attach) decode(d *Decoder) error {
	var err error
	if m.Name, err = d.ReadString(); err != nil {
		return err
	}
	if m.Cols, err = d.ReadU16(); err != nil {
		return err
	}
	if m.Rows, err = d.ReadU16(); err != nil {
		return err
	}
	if m.Xpixel, err = d.ReadU16(); err != nil {
		return err
	}
	if m.Ypixel, err = d.ReadU16(); err != nil {
		return err
	}
	{
		commandLen, err := d.ReadU32()
		if err != nil {
			return err
		}
		m.Command = make([]string, commandLen)
		for i := range m.Command {
			if m.Command[i], err = d.ReadString(); err != nil {
				return err
			}
		}
	}
	{
		envLen, err := d.ReadU32()
		if err != nil {
			return err
		}
		m.Env = make([]string, envLen)
		for i := range m.Env {
			if m.Env[i], err = d.ReadString(); err != nil {
				return err
			}
		}
	}
	if m.ScrollbackLines, err = d.ReadU32(); err != nil {
		return err
	}
	if m.CWD, err = d.ReadString(); err != nil {
		return err
	}
	if m.ReadOnly, err = d.ReadBool(); err != nil {
		return err
	}
	return nil
}

func (m *ClientsChanged) Type() uint8 { return TypeClientsChanged }

func (m *ClientsChanged) encode(e *Encoder) error {
	if err := e.WriteU16(m.Count); err != nil {
		return err
	}
	if err := e.WriteU16(m.Cols); err != nil {
		return err
	}
	if err := e.WriteU16(m.Rows); err != nil {
		return err
	}
	return nil
}

func (m *ClientsChanged) decode(d *Decoder) error {
	var err error
	if m.Count, err = d.ReadU16(); err != nil {
		return err
	}
	if m.Cols, err = d.ReadU16(); err != nil {
		return err
	}
	if m.Rows, err = d.ReadU16(); err != nil {
		return err
	}
	return nil
}

func (m *DaemonStatus) encode(e *Encoder) error {
	if err := e.WriteU32(m.PID); err != nil {
		return err
	}
	if err := e.WriteU32(m.Uptime); err != nil {
		return err
	}
	if err := e.WriteString(m.SocketPath); err != nil {
		return err
	}
	if err := e.WriteU32(m.RunningCount); err != nil {
		return err
	}
	if err := e.WriteU32(m.DeadCount); err != nil {
		return err
	}
	if err := e.WriteString(m.Version); err != nil {
		return err
	}
	return nil
}

func (m *DaemonStatus) decode(d *Decoder) error {
	var err error
	if m.PID, err = d.ReadU32(); err != nil {
		return err
	}
	if m.Uptime, err = d.ReadU32(); err != nil {
		return err
	}
	if m.SocketPath, err = d.ReadString(); err != nil {
		return err
	}
	if m.RunningCount, err = d.ReadU32(); err != nil {
		return err
	}
	if m.DeadCount, err = d.ReadU32(); err != nil {
		return err
	}
	if m.Version, err = d.ReadString(); err != nil {
		return err
	}
	return nil
}

func (m *Detach) Type() uint8 { return TypeDetach }

func (m *Detach) encode(e *Encoder) error {
	if err := e.WriteString(m.Name); err != nil {
		return err
	}
	return nil
}

func (m *Detach) decode(d *Decoder) error {
	var err error
	if m.Name, err = d.ReadString(); err != nil {
		return err
	}
	return nil
}

func (m *Dump) Type() uint8 { return TypeDump }

func (m *Dump) encode(e *Encoder) error {
	if err := e.WriteString(m.Name); err != nil {
		return err
	}
	if err := e.WriteU8(m.Format); err != nil {
		return err
	}
	return nil
}

func (m *Dump) decode(d *Decoder) error {
	var err error
	if m.Name, err = d.ReadString(); err != nil {
		return err
	}
	if m.Format, err = d.ReadU8(); err != nil {
		return err
	}
	return nil
}

func (m *DumpResponse) Type() uint8 { return TypeDumpResponse }

func (m *DumpResponse) encode(e *Encoder) error {
	if err := e.WriteBytes(m.Data); err != nil {
		return err
	}
	return nil
}

func (m *DumpResponse) decode(d *Decoder) error {
	var err error
	if m.Data, err = d.ReadBytes(); err != nil {
		return err
	}
	return nil
}

func (m *Error) Type() uint8 { return TypeError }

func (m *Error) encode(e *Encoder) error {
	if err := e.WriteU16(m.Code); err != nil {
		return err
	}
	if err := e.WriteString(m.Message); err != nil {
		return err
	}
	return nil
}

func (m *Error) decode(d *Decoder) error {
	var err error
	if m.Code, err = d.ReadU16(); err != nil {
		return err
	}
	if m.Message, err = d.ReadString(); err != nil {
		return err
	}
	return nil
}

func (m *Exited) Type() uint8 { return TypeExited }

func (m *Exited) encode(e *Encoder) error {
	if err := e.WriteI32(m.ExitCode); err != nil {
		return err
	}
	return nil
}

func (m *Exited) decode(d *Decoder) error {
	var err error
	if m.ExitCode, err = d.ReadI32(); err != nil {
		return err
	}
	return nil
}

func (m *Input) Type() uint8 { return TypeInput }

func (m *Input) encode(e *Encoder) error {
	if err := e.WriteBytes(m.Data); err != nil {
		return err
	}
	return nil
}

func (m *Input) decode(d *Decoder) error {
	var err error
	if m.Data, err = d.ReadBytes(); err != nil {
		return err
	}
	return nil
}

func (m *Kill) Type() uint8 { return TypeKill }

func (m *Kill) encode(e *Encoder) error {
	if err := e.WriteString(m.Name); err != nil {
		return err
	}
	return nil
}

func (m *Kill) decode(d *Decoder) error {
	var err error
	if m.Name, err = d.ReadString(); err != nil {
		return err
	}
	return nil
}

func (m *List) Type() uint8 { return TypeList }

func (m *List) encode(_ *Encoder) error { return nil }

func (m *List) decode(_ *Decoder) error { return nil }

func (m *OK) Type() uint8 { return TypeOK }

func (m *OK) encode(e *Encoder) error {
	if err := e.WriteString(m.SessionName); err != nil {
		return err
	}
	if err := e.WriteU16(m.Cols); err != nil {
		return err
	}
	if err := e.WriteU16(m.Rows); err != nil {
		return err
	}
	if err := e.WriteU32(m.PID); err != nil {
		return err
	}
	if err := e.WriteBool(m.Created); err != nil {
		return err
	}
	return nil
}

func (m *OK) decode(d *Decoder) error {
	var err error
	if m.SessionName, err = d.ReadString(); err != nil {
		return err
	}
	if m.Cols, err = d.ReadU16(); err != nil {
		return err
	}
	if m.Rows, err = d.ReadU16(); err != nil {
		return err
	}
	if m.PID, err = d.ReadU32(); err != nil {
		return err
	}
	if m.Created, err = d.ReadBool(); err != nil {
		return err
	}
	return nil
}

func (m *Output) Type() uint8 { return TypeOutput }

func (m *Output) encode(e *Encoder) error {
	if err := e.WriteBytes(m.Data); err != nil {
		return err
	}
	return nil
}

func (m *Output) decode(d *Decoder) error {
	var err error
	if m.Data, err = d.ReadBytes(); err != nil {
		return err
	}
	return nil
}

func (m *Prune) Type() uint8 { return TypePrune }

func (m *Prune) encode(_ *Encoder) error { return nil }

func (m *Prune) decode(_ *Decoder) error { return nil }

func (m *PruneResponse) Type() uint8 { return TypePruneResponse }

func (m *PruneResponse) encode(e *Encoder) error {
	if err := e.WriteU32(m.Count); err != nil {
		return err
	}
	return nil
}

func (m *PruneResponse) decode(d *Decoder) error {
	var err error
	if m.Count, err = d.ReadU32(); err != nil {
		return err
	}
	return nil
}

func (m *Resize) Type() uint8 { return TypeResize }

func (m *Resize) encode(e *Encoder) error {
	if err := e.WriteU16(m.Cols); err != nil {
		return err
	}
	if err := e.WriteU16(m.Rows); err != nil {
		return err
	}
	if err := e.WriteU16(m.Xpixel); err != nil {
		return err
	}
	if err := e.WriteU16(m.Ypixel); err != nil {
		return err
	}
	return nil
}

func (m *Resize) decode(d *Decoder) error {
	var err error
	if m.Cols, err = d.ReadU16(); err != nil {
		return err
	}
	if m.Rows, err = d.ReadU16(); err != nil {
		return err
	}
	if m.Xpixel, err = d.ReadU16(); err != nil {
		return err
	}
	if m.Ypixel, err = d.ReadU16(); err != nil {
		return err
	}
	return nil
}

func (m *Send) Type() uint8 { return TypeSend }

func (m *Send) encode(e *Encoder) error {
	if err := e.WriteString(m.Name); err != nil {
		return err
	}
	if err := e.WriteBytes(m.Data); err != nil {
		return err
	}
	return nil
}

func (m *Send) decode(d *Decoder) error {
	var err error
	if m.Name, err = d.ReadString(); err != nil {
		return err
	}
	if m.Data, err = d.ReadBytes(); err != nil {
		return err
	}
	return nil
}

func (m *SendKey) Type() uint8 { return TypeSendKey }

func (m *SendKey) encode(e *Encoder) error {
	if err := e.WriteString(m.Name); err != nil {
		return err
	}
	if err := e.WriteU32(m.KeyCode); err != nil {
		return err
	}
	if err := e.WriteU32(m.Mods); err != nil {
		return err
	}
	return nil
}

func (m *SendKey) decode(d *Decoder) error {
	var err error
	if m.Name, err = d.ReadString(); err != nil {
		return err
	}
	if m.KeyCode, err = d.ReadU32(); err != nil {
		return err
	}
	if m.Mods, err = d.ReadU32(); err != nil {
		return err
	}
	return nil
}

func (m *Session) encode(e *Encoder) error {
	if err := e.WriteString(m.Name); err != nil {
		return err
	}
	if err := e.WriteString(m.State); err != nil {
		return err
	}
	if err := e.WriteU16(m.Cols); err != nil {
		return err
	}
	if err := e.WriteU16(m.Rows); err != nil {
		return err
	}
	if err := e.WriteU32(m.PID); err != nil {
		return err
	}
	if err := e.WriteU32(m.CreatedAt); err != nil {
		return err
	}
	if err := e.WriteString(m.CWD); err != nil {
		return err
	}
	return nil
}

func (m *Session) decode(d *Decoder) error {
	var err error
	if m.Name, err = d.ReadString(); err != nil {
		return err
	}
	if m.State, err = d.ReadString(); err != nil {
		return err
	}
	if m.Cols, err = d.ReadU16(); err != nil {
		return err
	}
	if m.Rows, err = d.ReadU16(); err != nil {
		return err
	}
	if m.PID, err = d.ReadU32(); err != nil {
		return err
	}
	if m.CreatedAt, err = d.ReadU32(); err != nil {
		return err
	}
	if m.CWD, err = d.ReadString(); err != nil {
		return err
	}
	return nil
}

func (m *SessionStatus) encode(e *Encoder) error {
	if err := e.WriteString(m.Name); err != nil {
		return err
	}
	if err := e.WriteString(m.State); err != nil {
		return err
	}
	if err := e.WriteU16(m.Cols); err != nil {
		return err
	}
	if err := e.WriteU16(m.Rows); err != nil {
		return err
	}
	if err := e.WriteU32(m.PID); err != nil {
		return err
	}
	if err := e.WriteString(m.CWD); err != nil {
		return err
	}
	if err := e.WriteU32(m.ClientCount); err != nil {
		return err
	}
	if err := e.WriteU32(uint32(len(m.ClientVersions))); err != nil {
		return err
	}
	for _, v := range m.ClientVersions {
		if err := e.WriteString(v); err != nil {
			return err
		}
	}
	return nil
}

func (m *SessionStatus) decode(d *Decoder) error {
	var err error
	if m.Name, err = d.ReadString(); err != nil {
		return err
	}
	if m.State, err = d.ReadString(); err != nil {
		return err
	}
	if m.Cols, err = d.ReadU16(); err != nil {
		return err
	}
	if m.Rows, err = d.ReadU16(); err != nil {
		return err
	}
	if m.PID, err = d.ReadU32(); err != nil {
		return err
	}
	if m.CWD, err = d.ReadString(); err != nil {
		return err
	}
	if m.ClientCount, err = d.ReadU32(); err != nil {
		return err
	}
	{
		clientVersionsLen, err := d.ReadU32()
		if err != nil {
			return err
		}
		m.ClientVersions = make([]string, clientVersionsLen)
		for i := range m.ClientVersions {
			if m.ClientVersions[i], err = d.ReadString(); err != nil {
				return err
			}
		}
	}
	return nil
}

func (m *Sessions) Type() uint8 { return TypeSessions }

func (m *Sessions) encode(e *Encoder) error {
	if err := e.WriteU32(uint32(len(m.Sessions))); err != nil {
		return err
	}
	for i := range m.Sessions {
		if err := m.Sessions[i].encode(e); err != nil {
			return err
		}
	}
	return nil
}

func (m *Sessions) decode(d *Decoder) error {
	{
		sessionsLen, err := d.ReadU32()
		if err != nil {
			return err
		}
		m.Sessions = make([]Session, sessionsLen)
		for i := range m.Sessions {
			if err := m.Sessions[i].decode(d); err != nil {
				return err
			}
		}
	}
	return nil
}

func (m *State) Type() uint8 { return TypeState }

func (m *State) encode(e *Encoder) error {
	if err := e.WriteBytes(m.ScreenDump); err != nil {
		return err
	}
	if err := e.WriteU32(m.CursorRow); err != nil {
		return err
	}
	if err := e.WriteU32(m.CursorCol); err != nil {
		return err
	}
	if err := e.WriteBool(m.IsAlternateScreen); err != nil {
		return err
	}
	return nil
}

func (m *State) decode(d *Decoder) error {
	var err error
	if m.ScreenDump, err = d.ReadBytes(); err != nil {
		return err
	}
	if m.CursorRow, err = d.ReadU32(); err != nil {
		return err
	}
	if m.CursorCol, err = d.ReadU32(); err != nil {
		return err
	}
	if m.IsAlternateScreen, err = d.ReadBool(); err != nil {
		return err
	}
	return nil
}

func (m *Status) Type() uint8 { return TypeStatus }

func (m *Status) encode(e *Encoder) error {
	if err := e.WriteString(m.SessionName); err != nil {
		return err
	}
	return nil
}

func (m *Status) decode(d *Decoder) error {
	var err error
	if m.SessionName, err = d.ReadString(); err != nil {
		return err
	}
	return nil
}

func (m *StatusResponse) Type() uint8 { return TypeStatusResponse }

func (m *StatusResponse) encode(e *Encoder) error {
	if err := m.Daemon.encode(e); err != nil {
		return err
	}
	if m.Session == nil {
		if err := e.WriteU8(0); err != nil {
			return err
		}
	} else {
		if err := e.WriteU8(1); err != nil {
			return err
		}
		if err := m.Session.encode(e); err != nil {
			return err
		}
	}
	return nil
}

func (m *StatusResponse) decode(d *Decoder) error {
	if err := m.Daemon.decode(d); err != nil {
		return err
	}
	{
		flag, err := d.ReadU8()
		if err != nil {
			return err
		}
		if flag != 0 {
			m.Session = &SessionStatus{}
			if err := m.Session.decode(d); err != nil {
				return err
			}
		}
	}
	return nil
}

func newMessage(t uint8) (Message, error) {
	switch t {
	case TypeAttach:
		return &Attach{}, nil
	case TypeInput:
		return &Input{}, nil
	case TypeResize:
		return &Resize{}, nil
	case TypeDetach:
		return &Detach{}, nil
	case TypeList:
		return &List{}, nil
	case TypeKill:
		return &Kill{}, nil
	case TypeSend:
		return &Send{}, nil
	case TypeDump:
		return &Dump{}, nil
	case TypePrune:
		return &Prune{}, nil
	case TypeSendKey:
		return &SendKey{}, nil
	case TypeStatus:
		return &Status{}, nil
	case TypeOK:
		return &OK{}, nil
	case TypeError:
		return &Error{}, nil
	case TypeOutput:
		return &Output{}, nil
	case TypeState:
		return &State{}, nil
	case TypeSessions:
		return &Sessions{}, nil
	case TypeExited:
		return &Exited{}, nil
	case TypeDumpResponse:
		return &DumpResponse{}, nil
	case TypePruneResponse:
		return &PruneResponse{}, nil
	case TypeClientsChanged:
		return &ClientsChanged{}, nil
	case TypeStatusResponse:
		return &StatusResponse{}, nil
	default:
		return nil, fmt.Errorf("unknown message type: 0x%02x", t)
	}
}
